# Generated by Django 3.2.12 on 2023-02-16 04:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='deviceplc',
            name='home',
        ),
        migrations.AddField(
            model_name='deviceplc',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Код устройства'),
        ),
        migrations.AddField(
            model_name='deviceplc',
            name='device_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.devicemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceplc',
            name='device_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.devicetype'),
            preserve_default=False,
        ),
    ]
